### ISSUE TITLE
Remarques concernant le projet original

### ISSUE THREAD

**Issue by brunoilponseisae** [alexandreBerezin/topoguide-groupe-1#2]
Quelques remarques que j'ai notées sur le projet original que vous avez choisi:

- Création/Modification de sortie: 
  - Le projet crash si la date n'est pas renseignée correctement par l'utilisateur
  - Les données de sont pas validées (eg. possibilité d'entrer un nombre négatif de participants)
  - L'utilisateur passe par une page intermédiaire qui indique que la création ou la sauvegarde c'est bien passée. L'utilisateur attend inutilement et il ne comprend pas forcément s'il doit attendre.
  - On aurait aimé un widget adapté à la sélection de la date
- On aurait aimé que le path '/' présente une vue
- dans views.py : `itineraire_list = Itineraire.objects.order_by('titre')[:]` => A quoi sert [:]

**Comment by alexiaauddino** [comment]
Bonjour, j'ai fait les différentes corrections sur le dernier commit #eeeac80da3a0cb394638995ac220d4dc75f98e9e sur le main. 
[:] sert à tous afficher, mais ça n'est peut être pas nécessaire

**Comment by brunoilponseisae** [comment]
> Bonjour, j'ai fait les différentes corrections sur le dernier commit #eeeac80da3a0cb394638995ac220d4dc75f98e9e sur le main. [:] sert à tous afficher, mais ça n'est peut être pas nécessaire

Oui Sauf erreur ce n'est pas nécessaire.
